name: CI

on:
  push:
    branches:
      - main
      - master
    tags: ['*']
  pull_request:
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: read
      id-token: write
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        julia-version:
          - 'min'    # Minimum supported version from Project.toml
          - 'lts'    # Long Term Support version
          - '1'      # Latest stable 1.x release
          - 'pre'    # Latest prerelease (beta/rc)
          - 'nightly' # Nightly builds
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v5

      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}

      - uses: julia-actions/cache@v2

      - uses: julia-actions/julia-buildpkg@v1

      - name: Run tests (Linux with D-Bus suppression)
        if: runner.os == 'Linux'
        uses: julia-actions/julia-runtest@v1
        env:
          # Suppress D-Bus errors in Linux CI environment
          DBUS_SYSTEM_BUS_ADDRESS: ""
          DBUS_SESSION_BUS_ADDRESS: ""
          # Enable 2 threads for concurrency testing
          JULIA_NUM_THREADS: 2

      - name: Run tests (Windows/macOS)
        if: runner.os != 'Linux'
        uses: julia-actions/julia-runtest@v1
        env:
          # Enable 2 threads for concurrency testing
          JULIA_NUM_THREADS: 2

      - uses: julia-actions/julia-processcoverage@v1

      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          use_oidc: true
          flags: unittests
          fail_ci_if_error: false

